name: Vue build and test
on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'develop'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn run typecheck
      - run: yarn run test:unit
